### ISSUE TITLE
Username only set on return when hashref is passed to basic_auth()

### ISSUE THREAD

**Issue by dcoshea** [stregone/mojolicious-plugin-basicauthplus#5]
Thanks for the quick release for issue #4!  However, I found that the username is blank in the returned hashref unless you call `basic_auth()` with a hashref, e.g.:

    $self->basic_auth({realm => '...',
                       username => '...',
                       password => '...'});

but not if you don't pass `username` in the dict in that way, e.g.:

    $self->basic_auth('...' => {username => '...',
                                password => '...'});

I used this second scheme since that's what all the examples in the README file look like, and it also seems to be required if you want to use password file or LDAP authentication.

Maybe `basic_auth()` should call `_split_auth()` itself instead of leaving it to the `_check_*()` subs (and, in the case of using the callback, calling `split /:/, $auth, 2`), and then use the username returned by that?

**Comment by stregone** [comment]
D'oh!  I'll take a look at this as soon as my schedule permits, probably within a day or two.

**Comment by stregone** [comment]
I just pushed up a new version with a fix for this.  Let me know if it doesn't work for you.

**Comment by dcoshea** [comment]
It still doesn't work with LDAP authentication.  It looks like the code is designed only for the case where the username to be returned is provided by the caller, which isn't the case if you're authenticating against a password file or LDAP.

**Comment by stregone** [comment]
I see it.  Drat, that's what I get for being rambunctious.  Looks like I misplaced a line and made it too specific.  I have a fix, but I want to write a few more tests to make sure it's correct, and then I'll push an update.  Thanks for your patience and feedback.

**Comment by stregone** [comment]
Care to try it once more?

**Comment by xlat** [comment]
I was able to reproduce the issue, take a look at my modified `t/auth.t`. 
I suggest to split `$auth` to retrieve username rather than using `$usename` extracted from `_expected_auth`.

My patch is working fine, in my case at least.

**Comment by stregone** [comment]
Thanks!  I've been swamped with work from my day job, but I'll take a look asap.

**Comment by stregone** [comment]
Thanks.  I think we can close this issue now; however, if I am mistaken, please re-open this issue or open a new issue.
